name = "Beams"
uuid = "6a3f3b4c-7cdf-11e9-3de6-3b3783f4badb"
authors = ["ben "]
version = "0.1.0"

[deps]
GSL = "92c85e6c-cbff-5e0c-80f7-495c94daaecd"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
